config/routes.rb
AppAuction::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get '/search' => 'home#search', as: 'search'
  get '/users/payment' => 'users#payment', as: :payment
  post '/users/payment' => 'users#payment_post', as: :payment_post 
  resources :users, :only => [:show, :edit, :update, :payment]
  resources :mobile_apps, :except => [:show]
  resources :mobile_app_steps
  resources :home, :only => [:show, :index]
  get 'contacts/new', :as => "contact"
  post 'contacts/create'
  
  root :to => 'home#index'
  post '/screenshot_upload' => 'mobile_apps#screenshot_upload'
  get '/screenshot_upload_status' =>  'mobile_apps#screenshot_upload_status'
  delete '/screenshot_delete' =>  'mobile_apps#screenshot_delete'
  
  resources :auctions, :only => [:show] do
    get "/bids", :to => "auctions#bids", :as => :bids
  end
  post 'auctions/place_bid'
  post 'auctions/create_comments'
  post 'mobile_apps/create_comments'

  get "/payments", to: "payments#index", as: :auction_payments
  get "/payments/:id", to: "payments#show", as: :auction_payment
  get "/payments/:id/pay", to: "payments#pay", as: :auction_payment_pay
  post "/payments/:id/pay", to: "payments#pay_post", as: :auction_payment_pay_post
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :mobile_apps
  has_many :mobile_app_bids
  has_many :auctions, :through => :mobile_apps
  has_many :won_auctions, :through => :mobile_app_bids, :source => :won_auction
  has_many :payments
  has_many :paid_auctions, :through => :payments, :source => :auction
  has_many :paid_mobile_apps, :through => :paid_auctions, :source => :mobile_app
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # ROLES = [:buyer, :seller]

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  # validates :role, :presence => true, :inclusion => { :in => ROLES }
  validates :user_name, :presence => true, :uniqueness=>true
  scope :confirmed, -> { where('confirmed_at  is not null') }
  scope :not_confirmed, -> { where(confirmed_at: nil) }
  before_validation :set_created_by
  after_update :audit
  
  def set_created_by
    if AdminUser.current
      self.create_by = AdminUser.current.name
    else
      self.create_by = "Self Registration"
    end
  end
  
  def self.current
    Thread.current[:user]
  end
  
  def self.current=(user)
    Thread.current[:user] = user
  end

  def balanced_customer
    return Balanced::Customer.find(self.customer_uri) if self.customer_uri.present?
    customer = self.class.create_balanced_customer(:name => self.name, :email  => self.email)
    self.customer_uri = customer.uri
    self.save
    customer
  end

  def payment_information_present?
    self.customer_uri.present?
  end

  def self.create_balanced_customer(params = {})
    begin
      Balanced::Marketplace.mine.create_customer(
        :name   => params[:name],
        :email  => params[:email]
        )
    rescue
      raise 'There was an error adding a customer'
    end
  end
  
  
  def audit
    if self.changed?
      comment = ActiveAdmin::Comment.new
      comment.resource = self
      comment.author = User.current rescue nil
      comment.namespace = "admin"
      msg = "Values Changed <br />"
      self.changes.each do |k, v|
        if k.upcase == "NAME" || k.upcase == "EMAIL" || k.upcase == "COMMENT_NOTIFICATION_ENABLED"
          msg << "#{k.upcase}: #{v[0]} > #{v[1]} <br/>" unless k.eql?("updated_at")
          comment.body = "#{msg}"  rescue nil
          comment.save
        end
      end
    end
  end
  
  def is_admin?
    false
  end

  def confirm!
    UserMailer.welcome(self).deliver
    super
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate_user!, :only => :show
  before_filter :confirm_correct_user, :only => [:edit, :update, :payment, :payment_post]
  
  def show
    @user = User.find(params[:id])
  end

  def edit
  end
  
  def update
    if params[:user][:email] && @user.confirmed? && (@user.email != params[:user][:email])
      @user.confirmed_at = nil
      Devise::Mailer.confirmation_instructions(@user, nil).deliver
      @user.save(:validate => false)
    end
    if @user.update_attributes(user_params)
      if @user.email_changed?
        sign_out @user
        flash[:notice] = "Profile updated successfully."
        redirect_to root_path
      else
        flash[:notice] = "Profile updated successfully."
        redirect_to user_path(params[:id])
      end
    else
      flash[:error] = "Profile update error."
      render :action => 'edit'
    end
    
  end

  def payment
    if @user.customer_uri.present?
      customer_account = Balanced::BankAccount.find(@user.customer_uri)
      bank_account = Balanced::BankAccount.find(customer_account.bank_accounts_uri).attributes["items"].first
    elsif @user.bank_account_uri.present?
      bank_account = Balanced::BankAccount.find(@user.bank_account_uri).attributes
    end
    if bank_account.present?
      @bank_name = bank_account["bank_name"]
      @account_number = bank_account["account_number"]
      @routing_number = bank_account["routing_number"]
      @account_type = bank_account["type"]
    end
  end

  def payment_post
    balanced_user = @user.balanced_customer #Retrieve or create balanced customer
    balanced_user.add_bank_account(params[:bank_account_uri]) #Associate bank account with customer
    @user.bank_account_uri = params[:bank_account_uri]
    if @user.save!
      flash[:notice] = "Account successfully added"
    else
      flash[:error] = "There was an error with your bank account information. Please try again."
    end
    redirect_to payment_path
  end
  
  private


  def confirm_correct_user
    if user_signed_in? && current_user.present?
      @user = current_user
    else
      flash[:error] = "Access Denied"
      redirect_to root_url 
    end
  end


  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :user_name, :street_address, :zipcode, :comment_notification_off)
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
  def auction_label_class(status)
    case status
    when "active"
      "success"
    when "ended"
      ""
    when "not yet started"
      ""
    else
      "alert"
    end
  end
end

app/views/users/_payment_fields.html.haml
.row
  .large-12.columns
    .control-group
      = label_tag(:name, 'Name')
      = text_field_tag(:name, @user.name.present? ? @user.name : nil, :class => "name", :id => "name", :placeholder => "John Smith")    
      %small
.row
  .large-12.columns
    .control-group
      = label_tag(:email, 'Email')
      = text_field_tag(:email, @user.email.present? ? @user.email : nil, :class => "email", :id => "email", :placeholder => "jsmith@example.com")    
      %small
.row 
  .large-12.columns
    .control-group
      = label_tag(:street_address, 'Street Address')
      = text_field_tag(:street_address, @user.street_address.present? ? @user.street_address : nil, :class => "street_address", :id => "street_address", :placeholder => "1600 Pennsylvania Avenue")
      %small 
.row 
  .large-12.columns
    .control-group
      = label_tag(:zipcode, 'Zipcode')
      = text_field_tag(:zipcode, @user.zipcode.present? ? @user.zipcode : nil, :class => "zipcode", :id => "zipcode", :placeholder => "20500")
      %small      
.row
  .large-12.columns
    .control-group
      = label_tag(:date_of_birth_month, 'Date of Birth')
      .row
        .large-6.columns
          = select_month(1, {}, { :class => 'span1', :id => 'guest-date_of_birth_month', :name => 'date_of_birth_month' })
          %small
        .large-6.columns
          = select_tag(:date_of_birth_year, options_for_select(1900.upto(Time.now.year).map{ |num| [num,num] }), :class => 'span1', :id => 'guest-date_of_birth_year')
          %small
.row
  .large-12.columns
    .control-group
      = label_tag(:account_number, "Bank Account Number")
      = text_field_tag(:account_number, nil, :class => "account_number", :id => "account_number", :placeholder => "7777777777777")
      %small
.row
  .large-12.columns
    .control-group
      = label_tag(:routing_number, "Bank Routing Number")
      = text_field_tag(:routing_number, nil, :class => "routing_numner", :id => "routing_numner", :placeholder => "100000000" )
      %small
.row
  .large-12.columns
    .control-group
      = label_tag(:account_type, "Bank Account Type")
      = select_tag(:account_type, options_for_select([["Checkings Account", "checking"], ["Savings Account", "savings"]]))
    %small

app/views/users/edit.html.haml
%section.orange-background
  .row
    .small-12.large-12.columns
      %h1 Edit Account

%section.white-background
  .row
    .small-12.large-4.columns
      = image_tag avatar_url(@user, 200), :id => "profile-avatar"
      = link_to "Change Profile Image", "http://en.gravatar.com/", :target => "_blank", :class => "button secondary small", :id => "profile-avatar-change"
      = link_to "Edit Payment Information", payment_path, :class => "button small"

    .small-12.large-8.columns
      = simple_form_for @user do |f|
        = f.error_notification
        = display_base_errors @user
        .row
          .large-12.columns
            = f.label "Username"
            = f.text_field :user_name, :disabled => true
        .row
          .large-12.columns
            = f.label "Name"
            = f.input_field :name
        .row
          .large-12.columns
            = f.label "Email"
            = f.input_field :email
        .row
          .large-12.columns
            = f.input :street_address
        .row
          .large-12.columns
            = f.input :zipcode
        .row
          .large-12.columns
            = f.input :comment_notification_off, :label => "Turn off comment email notifications from App Listing Site"
        .row
          .large-12.columns
            = f.submit "Update", :class => "button success"
            or
            = link_to 'Cancel', user_path(@user)

app/views/users/payment.html.haml
- content_for :head do
  = javascript_include_tag 'balanced_payments'

%section.orange-background
  .row
    .large-12.columns
      %h1 Account Payment Information

- if @bank_name.present?
  %section.gray-background
    .row
      .large-12.columns
        %h2 Current account
        %h6 Bank Name:
        = @bank_name
        %h6 Account Number:
        = @account_number.upcase
        %h6 Routing Number:
        = @routing_number
        %h6 Account Type:
        = @account_type.upcase

%section.white-background
  .row
    .large-12.columns
      %h2 New Account
      = form_tag({:controller => 'users', :action => 'payment_post', :method => 'post'},{:id => 'bank-account-form'}) do
        = render :partial => "payment_fields"
        %button{:type => "submit"}
          - if @bank_name.present?
            Change Bank Account
          - else
            Add Bank Account

<script type="text/javascript" src="https://js.balancedpayments.com/v1/balanced.js"></script>

app/views/users/show.html.haml
%section.orange-background
  .row
    .small-4.large-3.columns
      = image_tag avatar_url(@user, 200), :id => "profile-avatar"
      - if user_signed_in? && current_user == @user
        = link_to "Change Profile Image", "http://en.gravatar.com/", :target => "_blank", :class => "button secondary small", :id => "profile-avatar-change"

    .small-8.large-9.columns
      - if user_signed_in? && current_user == @user
        = link_to "Account Settings", edit_user_path(@user), :class => "button right", :id => "profile-edit"

      %h1= @user.name

      %span.profile-label Member Since:
      = @user.confirmed_at.present? ? @user.confirmed_at.strftime("%b %d, %Y") : "N/A"

      #profile-apps
        .row
          .small-4.large-4.columns.text-center
            .profile-label Apps Listed
            .profile-value= @user.auctions.size unless @user.auctions.nil?

          .small-4.large-4.columns.text-center
            .profile-label Apps Sold
            .profile-value= @user.auctions.where(:sold => true).size unless @user.auctions.nil?

          .small-4.large-4.columns.text-center
            .profile-label Apps Bought
            .profile-value= @user.won_auctions.size

- if user_signed_in? && current_user == @user
  %section.gray-background
    .row
      .small-12.large-12.columns
        %h3 Apps submitted for sale

        - if @user.mobile_apps.any?
          %table
            %tr
              %th
                App Name
              %th
                Type
              %th
                Store Verification
              %th
                Verification Token
              %th
                Auction
              %th
                Bids
              %th
                Actions
            - @user.mobile_apps.each do |mobile_app|
              %tbody
                %tr
                  %td
                    = link_to mobile_app.title, auction_path(mobile_app)
                  %td
                    = mobile_app.ios? ? "iOS" : "Android"
                  %td
                    - if mobile_app.published?
                      .label.round.success
                        Verified
                    - else
                      .label.round.alert
                        = mobile_app.state.titlecase
                  %td
                    .app-verification-token
                      = link_to "Show token", "#", :class => "show-token"
                      %div.the-token
                        = mobile_app.verification_token
                  %td
                    - if mobile_app.auction.present?
                      .label.round{:class => auction_label_class(mobile_app.auction.state)}
                        = mobile_app.auction.state.titleize
                    - else
                      .label.round.alert
                        No auction data
                  %td.text-center
                    = link_to mobile_app.mobile_app_bid.size, auction_bids_path(mobile_app)
                  %td
                    - if mobile_app.auction.ended?
                      %i Auction ended
                    - else
                      = link_to "Edit Listing", edit_mobile_app_path(mobile_app), :class => "button tiny secondary"
        - else
          .panel
            No apps listed.


%section.white-background
  .row
    .small-12.large-7.columns
      %h3 Apps Sold

      - if @user.auctions.where(:sold => true).any?
        %table
          %tr
            %th
              App Name
            %th
              Type
            %th
              Min Purchase Price
            %th
              Sell Price
            %th
              No. of bids
          - @user.mobile_apps.each do |mobile_app|
            - if mobile_app.auction.sold?
              %tbody
                %tr
                  %td
                    = link_to mobile_app.title, auction_path(mobile_app.id)
                  %td
                    = mobile_app.ios? ? "iOS" : "Android"
                  %td.text-center
                    = number_to_currency(mobile_app.minimum_purchase_price, :unit => "$")
                  %td
                    = mobile_app.auction.present? ? number_to_currency(mobile_app.auction.sell_price_usd.presence || 0) : "N/A"
                  %td.text-center
                    = link_to mobile_app.mobile_app_bid.size, auction_bids_path(mobile_app)
      - else
        .panel
          No apps listed.

    .small-12.large-5.columns
      %h3 Apps purchased

      - if @user.paid_mobile_apps.any?
        %table
          %tr
            %th
              App Name
            %th
              Type
            %th
              Price
          - @user.paid_mobile_apps.each do |mobile_app|
            %tbody
              %tr
                %td
                  = link_to mobile_app.title, auction_path(mobile_app.id)
                %td
                  = mobile_app.ios? ? "iOS" : "Android"
                %td
                  = mobile_app.auction.present? ? number_to_currency(mobile_app.auction.sell_price_usd.presence || 0) : "N/A"
      - else
        .panel
          No apps listed.