config/routes.rb
AppAuction::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get '/search' => 'home#search', as: 'search'
  get '/users/payment' => 'users#payment', as: :payment
  post '/users/payment' => 'users#payment_post', as: :payment_post 
  resources :users, :only => [:show, :edit, :update, :payment]
  resources :mobile_apps, :except => [:show]
  resources :mobile_app_steps
  resources :home, :only => [:show, :index]
  get 'contacts/new', :as => "contact"
  post 'contacts/create'
  
  root :to => 'home#index'
  post '/screenshot_upload' => 'mobile_apps#screenshot_upload'
  get '/screenshot_upload_status' =>  'mobile_apps#screenshot_upload_status'
  delete '/screenshot_delete' =>  'mobile_apps#screenshot_delete'
  
  resources :auctions, :only => [:show] do
    get "/bids", :to => "auctions#bids", :as => :bids
  end
  post 'auctions/place_bid'
  post 'auctions/create_comments'
  post 'mobile_apps/create_comments'

  get "/payments", to: "payments#index", as: :auction_payments
  get "/payments/:id", to: "payments#show", as: :auction_payment
  get "/payments/:id/pay", to: "payments#pay", as: :auction_payment_pay
  post "/payments/:id/pay", to: "payments#pay_post", as: :auction_payment_pay_post
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_filter :authenticate_user!
  def new
    @message = Message.new
  end
  
  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Your message has been sent - App Listing support will get back to you shortly.")
    else
      flash.now.alert = "Name, Email, Subject and Message can't be blank"
      render :new
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/new.html.haml
%section.orange-background
  .row
    .large-12.columns
      %h1 Contact Us

%section.gray-background
  .row
    .large-12.columns
      = form_for @message, :url => contacts_create_path do |form|
        .row
          .large-12.columns
            = form.label "Your Name *"
            = form.text_field :name
        .row
          .large-12.columns
            = form.label "Your Email *"
            = form.text_field :email
        .row
          .large-12.columns
            = form.label :phone
            = form.text_field :phone
        .row
          .large-12.columns
            = form.label "Subject *"
            = form.text_field :subject
        .row
          .large-12.columns
            = form.label "Message *"
            = form.text_area :body
        .row
          .large-12.columns
            = form.submit "Send", :class => "button"