config/routes.rb
AppAuction::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get '/search' => 'home#search', as: 'search'
  get '/users/payment' => 'users#payment', as: :payment
  post '/users/payment' => 'users#payment_post', as: :payment_post 
  resources :users, :only => [:show, :edit, :update, :payment]
  resources :mobile_apps, :except => [:show]
  resources :mobile_app_steps
  resources :home, :only => [:show, :index]
  get 'contacts/new', :as => "contact"
  post 'contacts/create'
  
  root :to => 'home#index'
  post '/screenshot_upload' => 'mobile_apps#screenshot_upload'
  get '/screenshot_upload_status' =>  'mobile_apps#screenshot_upload_status'
  delete '/screenshot_delete' =>  'mobile_apps#screenshot_delete'
  
  resources :auctions, :only => [:show] do
    get "/bids", :to => "auctions#bids", :as => :bids
  end
  post 'auctions/place_bid'
  post 'auctions/create_comments'
  post 'mobile_apps/create_comments'

  get "/payments", to: "payments#index", as: :auction_payments
  get "/payments/:id", to: "payments#show", as: :auction_payment
  get "/payments/:id/pay", to: "payments#pay", as: :auction_payment_pay
  post "/payments/:id/pay", to: "payments#pay_post", as: :auction_payment_pay_post
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  belongs_to :auction

  after_create :send_payment_made_notification

  protected

  def send_payment_made_notification
    AuctionsMailer.payment_made(self.user, self.auction.mobile_app, self.auction).deliver
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @paid_auctions = current_user.paid_auctions
    @unpaid_auctions = Auction.where(:winning_bid_id => current_user.mobile_app_bids.pluck(:id)).where("sold IS NULL or sold IS FALSE")
  end

  def show
    @payment = current_user.payments.find(params[:id])
    @auction = @payment.auction
    debit = Balanced::Debit.find(@payment.debit_uri)
    @last_four = debit.source.last_four
  end

  def pay
    @auction = current_user.won_auctions.find(params[:id])
    @user = current_user
    if @user.customer_uri.present?
      customer_account = Balanced::BankAccount.find(@user.customer_uri)
      bank_account = Balanced::BankAccount.find(customer_account.bank_accounts_uri).attributes["items"].first
    elsif @user.bank_account_uri.present?
      bank_account = Balanced::BankAccount.find(@user.bank_account_uri).attributes
    end
    if bank_account.present?
      @bank_name = bank_account["bank_name"]
      @account_number = bank_account["account_number"]
      @routing_number = bank_account["routing_number"]
      @account_type = bank_account["type"]
    else
      flash[:error] = "You need to enter your payment information before you can pay for an auction. <a href='/users/payment'>Click here to add your account information</a>".html_safe
      redirect_to auction_payments_path
    end
  end

  def pay_post
    @user = current_user
    @auction = current_user.won_auctions.find(params[:id])
    if @user.customer_uri.present?
      user_account = Balanced::Customer.find(@user.customer_uri)
    else
      user_account = @user.balanced_customer
    end
    if params[:card_uri].present?
      user_account.add_card(params[:card_uri])
      auction_owner_account = Balanced::BankAccount.find(@auction.owner.customer_uri)

      winning_bid_value = @auction.winning_bid.bid_value * 100
      @payment = @user.payments.where(:amount => winning_bid_value, :auction_id => @auction.id).first_or_initialize
      if @payment.new_record?
        debit = user_account.debit(:amount => winning_bid_value, :description => "App Listing - #{@auction.mobile_app.title}", :on_behalf_of => auction_owner_account)
        credit = auction_owner_account.credit(:amount => winning_bid_value, :description => "App Listing - #{@auction.mobile_app.title} - #{@user.name}(#{@user.email})" )
        @payment.credit_uri = credit.uri
        @payment.debit_uri = debit.uri
        @auction.sold = true
        if @payment.save! && @auction.save!(:validate => false)
          flash[:notice] = "You have successfully bought #{@auction.mobile_app.title} for $#{(winning_bid_value/100).to_i}"
          redirect_to auction_payments_path
        else
          flash[:error] = "Your payment was not successful. Please try again later."
          render :pay
        end
      else
        flash[:error] = "You've already fully paid for this application."
        render :pay
      end
    else
      flash[:error] = "Something went wrong. Please try again later.".html_safe
      redirect_to auction_payments_path
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/index.html.haml
%section#show-details.gray-background
  .row
    .large-12.columns
      %h2
        My Payments 
  .row
    .large-12.columns
      .white-box-shadow
        %h3
          Auctions you have successfully paid for
        - if @paid_auctions.any?
          .panel
            %ul
              -@paid_auctions.each do |auction|
                %li
                  = link_to "Payment of #{number_to_currency(auction.winning_bid.bid_value, :precision => 0)} was recieved for \"#{auction.mobile_app.title}\" on #{auction.payment.created_at.strftime("%m/%d/%y")}", auction_payment_path(auction.payment)
        - else
          .panel.text-center
            No paid auctions.
  .row
    .large-12.columns
      .white-box-shadow
        %h3
          Auctions still needing payment
        - if @unpaid_auctions.any?
          .panel
            %ul
              -@unpaid_auctions.each do |auction|
                %li
                  = link_to "Payment of #{number_to_currency(auction.winning_bid.bid_value, :precision => 0)} needed for #{auction.mobile_app.title}", auction_payment_pay_path(auction)
        - else
          .panel.text-center
            No unpaid auctions.

app/views/payments/pay.html.haml
- content_for :head do
  = javascript_include_tag 'payments'
%section#show-details.gray-background
  .row
    .large-12.columns
      %h2.text-center
        = "Payment for #{@auction.mobile_app.title}"
  .row
    .large-6.large-centered.columns
      = form_tag({:controller => 'payments', :action => 'pay_post', :method => 'post'}, {:id => "payment-form"}) do
        .row
          .large-12.columns
            = label_tag(:payee_name, "Payee Name", :class => "required")
            = text_field_tag(:payee_name, current_user.name, :type => "text", :class => "name", :id => "guest_name", :placeholder => "John Smith", :required => true, :disabled => true)
        .row
          .large-12.columns
            = label_tag(:guest_email, "Payee Email", :class => "required")
            = text_field_tag(:guest_email, current_user.email, :type => "email", :class => "email", :id => "guest_email", :placeholder => "jsmith@example.com", :required => true, :disabled => true)
        .row
          .large-12.columns
            = label_tag(:amount, "Amount to pay (in dollars)", :class => "required")
            = text_field_tag(:amount, number_to_currency(@auction.winning_bid.bid_value, :precision => 0), :class => "amount", :id => "contribution_amount", :placeholder => "123.45", :required => true, :disabled => true)
        .row
          .large-12.columns
            .control-group
              = label_tag :card_number, :class => "required" do
                %span Credit Card Number
                %small Required
              .input
                = text_field_tag(:card_number, nil,  :class => 'cc-number', :id => 'card_number', :placeholder => "•••• •••• •••• ••••", :required => true)
        .row
          .large-12.columns
            .row
              .large-8.columns
                .control-group
                  = label_tag :'exp-month' do
                    %span Expires (MM/YYYY)
                    %small Required
                  .row.collapse
                    .large-4.columns
                      .input
                        = text_field_tag(:'expiration_month', nil, { :placeholder => "MM", :class => "cc-em sensitive", size: "2", type: "text", :required => true} )
                    .large-8.columns
                      .input
                        = text_field_tag(:'expiration_year', nil, { :placeholder => "YYYY", :class => "cc-ey sensitive", size: "4", type: "text", :required => true } )
              .large-4.columns
                .control-group
                  = label_tag :security_code, :class => "required" do
                    %span Security Code
                    %small Required
                  .input
                    = text_field_tag(:security_code, nil, :class => 'cc-csc', :required => true, :id => 'security_code', :placeholder => "•••")
        .row
          .large-4.columns
            .control-group
              = label_tag :billing_zip_code, :class => "required" do
                %span Billing Zipcode
                %small Required
              .input
                = text_field_tag(:postal_code, nil, :class => "zip", :required => true, :placeholder => "48104", :id => 'postal_code')
        .row
          .large-12.columns.texzt-center
            %button{:type => "submit", :class => "#{"disabled" if !@bank_name.present?}"}
              - if @bank_name.present?
                Pay for App
              - else
                You cannot pay for this app

<script type="text/javascript" src="https://js.balancedpayments.com/v1/balanced.js"></script>

app/views/payments/show.html.haml
%section#show-details.gray-background
  .row
    .large-12.columns
      %h2.text-center
        = "Payment for #{@auction.mobile_app.title}"
  .row
    .large-6.large-centered.columns.panel
      .row
        .large-6.columns
          %h6 Mobile App Purchased
        .large-6.columns
          = link_to @auction.mobile_app.title, auction_path(@auction.mobile_app)
      .row
        .large-6.columns
          %h6 Payee Name
        .large-6.columns
          = @payment.user.name
      .row
        .large-6.columns
          %h6 Payee Email
        .large-6.columns
          = @payment.user.email
      .row
        .large-6.columns
          %h6 Amount Paid
        .large-6.columns
          = number_to_currency((@payment.amount/100).to_i, :precision => 0)
      .row
        .large-6.columns
          %h6 Credit Card #
        .large-6.columns
          = "XXXX-XXXX-XXXX-#{@last_four}"
      .row
        .large-6.columns
          %h6 Purchased on
        .large-6.columns
          = @payment.created_at.strftime("%m/%d/%y")

    .row
      .large-6.large-centered.columns
        = link_to "Back to All Payments", auction_payments_path, :class => "button"