config/routes.rb
AppAuction::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get '/search' => 'home#search', as: 'search'
  get '/users/payment' => 'users#payment', as: :payment
  post '/users/payment' => 'users#payment_post', as: :payment_post 
  resources :users, :only => [:show, :edit, :update, :payment]
  resources :mobile_apps, :except => [:show]
  resources :mobile_app_steps
  resources :home, :only => [:show, :index]
  get 'contacts/new', :as => "contact"
  post 'contacts/create'
  
  root :to => 'home#index'
  post '/screenshot_upload' => 'mobile_apps#screenshot_upload'
  get '/screenshot_upload_status' =>  'mobile_apps#screenshot_upload_status'
  delete '/screenshot_delete' =>  'mobile_apps#screenshot_delete'
  
  resources :auctions, :only => [:show] do
    get "/bids", :to => "auctions#bids", :as => :bids
  end
  post 'auctions/place_bid'
  post 'auctions/create_comments'
  post 'mobile_apps/create_comments'

  get "/payments", to: "payments#index", as: :auction_payments
  get "/payments/:id", to: "payments#show", as: :auction_payment
  get "/payments/:id/pay", to: "payments#pay", as: :auction_payment_pay
  post "/payments/:id/pay", to: "payments#pay_post", as: :auction_payment_pay_post
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert-box{:id => "flash_#{name}", :class => name}
      .row
        .large-12.columns
          = msg

app/views/layouts/_navigation.html.haml
.contain-to-grid
  %nav.top-bar
    %ul.title-area
      %li.name
        %h1
          = link_to root_path, :class => 'brand' do
            = image_tag "app-listing-logo.png"
    %section.top-bar-section
      %ul.left
        %li.has-form
          = form_tag(search_path, method: "get") do
            .row.collapse
              .large-8.small-9.columns
                = text_field_tag(:q, "", :placeholder => "Find Stuff")
              .large-4.small-3.columns
                = submit_tag("Search", :class => "button secondary expand")
      %ul.right
        %li= link_to 'Contact Us', contact_path
        - if user_signed_in?
          %li= link_to 'My Profile', user_path(current_user.id)
          %li= link_to 'My Payments', auction_payments_path
          %li= link_to 'Submit App', new_mobile_app_path
          %li= link_to 'Logout', destroy_user_session_path, :method=>'delete'
        - else
          %li= link_to 'Login', new_user_session_path
          %li= link_to 'Sign up', new_user_registration_path, :class => 'sign-up'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "#{t(:app_name)}"
    %meta{:content => content_for?(:description) ? yield(:description) : "no description", :name => "description"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header
      = render 'layouts/navigation'
      = render 'layouts/messages'
    %section#main{:role => "main"}
      = yield
      %section#follow-us
        .row
          .large-12.columns
            .social-links
              = link_to image_tag("social-twitter.png"), "#", :title => "App Listing on Twitter"
              = link_to image_tag("social-facebook.png"), "#", :title => "App Listing on Facebook"
            %h2 Follow us to keep up with the latest news!
      %footer
        .row
          .large-12.columns
            &copy; #{Date.today.year} App Listing All Rights Reserved